/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 96;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 97;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 98;
  /** RegularExpression Id. */
  int INT = 100;
  /** RegularExpression Id. */
  int OCT = 101;
  /** RegularExpression Id. */
  int HEX = 102;
  /** RegularExpression Id. */
  int STRING = 103;
  /** RegularExpression Id. */
  int ID = 104;
  /** RegularExpression Id. */
  int LETTER = 105;
  /** RegularExpression Id. */
  int DIGIT = 106;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"*\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"+\"",
    "\"/\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"Absyn\"",
    "\"AddExpr\"",
    "\"AndExpr\"",
    "\"ArrayExpr\"",
    "\"ArrayType\"",
    "\"AssignableExpr\"",
    "\"AssignStmt\"",
    "\"BinOpExpr\"",
    "\"BlockStmt\"",
    "\"boolean\"",
    "\"BooleanType\"",
    "\"CallExpr\"",
    "\"class\"",
    "\"ClassDecl\"",
    "\"DivExpr\"",
    "\"else\"",
    "\"EqualExpr\"",
    "\"Expr\"",
    "\"extends\"",
    "\"false\"",
    "\"FalseExpr\"",
    "\"FieldExpr\"",
    "\"Formal\"",
    "\"GreaterExpr\"",
    "\"IdentifierExpr\"",
    "\"IdentifierType\"",
    "\"if\"",
    "\"IfStmt\"",
    "\"int\"",
    "\"IntegerLiteral\"",
    "\"IntegerType\"",
    "\"LesserExpr\"",
    "\"main\"",
    "\"MethodDecl\"",
    "\"MulExpr\"",
    "\"NegExpr\"",
    "\"new\"",
    "\"NewArrayExpr\"",
    "\"NewObjectExpr\"",
    "\"NotEqExpr\"",
    "\"NotExpr\"",
    "\"NullExpr\"",
    "\"OrExpr\"",
    "\"Program\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"Stmt\"",
    "\"String\"",
    "\"StringLiteral\"",
    "\"SubExpr\"",
    "\"this\"",
    "\"ThisExpr\"",
    "\"ThreadDecl\"",
    "\"true\"",
    "\"TrueExpr\"",
    "\"Type\"",
    "\"VarDecl\"",
    "\"void\"",
    "\"VoidDecl\"",
    "\"while\"",
    "\"WhileStmt\"",
    "\"Xinu\"",
    "\"XinuCallExpr\"",
    "\"XinuCallStmt\"",
    "\"public_static_void\"",
    "\"Thread\"",
    "\"synchronized\"",
    "\"AbstractList\"",
    "\"null\"",
    "\"//\"",
    "<token of kind 94>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 99>",
    "<INT>",
    "<OCT>",
    "<HEX>",
    "<STRING>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"||\"",
  };

}
